project:
  type: website
lang: en

website:
  title: "Francisco N. Ramos"
  site-url: "https://francisconramos.com"
  description: "Lab Manager & Clinical Psychology Researcher – personal site and science communication blog."
  favicon: favicon.ico

  navbar:
    background: dark
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "Contact"
        file: contact.qmd
    right:
      - icon: github
        href: https://github.com/Pachirisu1247
        aria-label: GitHub

  page-footer:
    left: "© 2025 Francisco N. Ramos"
    right: "Built with Quarto"
    background: "#212529"
    foreground: "#b0b0b0"
    border: false

  search: true

  # ✅ SEO + Schema.org metadata
  metadata:
    - name: description
      content: "Francisco N. Ramos – Lab Manager & Clinical Psychology Researcher at USC"
    - name: author
      content: "Francisco N. Ramos"
    - name: robots
      content: index, follow
    - name: viewport
      content: width=device-width, initial-scale=1
    - script:
        type: application/ld+json
        content: |
          {
            "@context": "https://schema.org",
            "@type": "Person",
            "name": "Francisco Nicolás Ramos",
            "alternateName": "Frankie Ramos",
            "url": "https://francisconramos.com",
            "image": "https://francisconramos.com/Francisco%20DTX.png",
            "jobTitle": "Lab Manager & Clinical Psychology Researcher",
            "affiliation": {
              "@type": "Organization",
              "name": "University of Southern California",
              "url": "https://usc.edu"
            },
            "sameAs": [
              "https://github.com/Pachirisu1247",
              "https://mmmlab.rbind.io/"
            ]
          }

format:
  html:
    theme:
      dark: darkly
    css: styles.css
    toc: false
    includes:
      after-body: custom.js

