project:
  type: website

website:
  title: "Francisco N. Ramos"
  description: "Lab Manager & Clinical Psychology Researcher – personal site and science communication blog."
  site-url: "https://francisconicolasramos.github.io/"
  navbar:
    background: dark
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "Contact"
        file: contact.qmd
    right: []
  page-footer:
    left: "© 2025 Francisco Nicolás Ramos"
    right: "Built with Quarto"
  search: true

format:
  html:
    theme:
      dark: darkly
    css: styles.css
    toc: false
