project:
  type: website

website:
  title: "Francisco Nicolás Ramos"
  description: "Lab Manager & Clinical Psychology Researcher – personal site and science communication blog."
  # URL of the site. This can be updated once the rbind.io domain is configured.
  site-url: "https://francisconicolasramos.github.io/"
  navbar:
    # Use a dark navbar to complement the dark theme.
    background: dark
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "Contact"
        file: contact.qmd
    right: []
  page-footer:
    left: "© 2025 Francisco Nicolás Ramos"
    right: "Built with Quarto"
  search: true

format:
  html:
    theme:
      dark: darkly
    css: styles.css
    toc: false
