---
title: "Home"
---

# Welcome



Hello! I'm **Francisco Nicolas Ramos** (Frankie) -- **Lab Manager** and **clinical psychology researcher**. I currently manage the **Depression Treatment Laboratory** at the University of Southern California, where I oversee daily operations of an NIMH-funded randomized clinical trial testing metaverse-based, peer-supported mental health interventions. My work spans data management and analysis, recruitment and mentorship of research assistants, and collaboration with partners at Vanderbilt University, Innerworld Inc., and other institutions.

Outside the lab, I contribute to the **Measurement & Multilevel Modeling Lab** at USC on science communication projects for psychologists and systematic reviews of measurement instruments. I also collaborate internationally with research groups in Spain on studies addressing mental health disorders and have presented my work at numerous conferences. I earned my B.A. in **Psychology and Economics** (Magna Cum Laude) from USC and am passionate about advancing mental health research and communicating science effectively. This site is a space to share more about my work, host my CV, and publish tutorials and posts on science communication.


## Curriculum Vitae

My full curriculum vitae is embedded below. Use the embedded viewer to read directly or the link to download a copy.

<iframe src="cv.pdf" style="width:100%; height:600px; border:none;">Your browser does not support iframes.</iframe>

If the embedded PDF does not display, use the following link to download it:

- [Download CV](cv.pdf)
